### ISSUE TITLE
Blue window border when containing Form inherits from Ribbon instead of inheriting from Form and Black Tab names background when changing orb style at runtime

### ISSUE THREAD

**Issue by jmaultby** [RibbonWinForms/RibbonWinForms#19]
Hi Hoping someone can help me with where to resolve these issues in the source code.
Using VS2017, assembly version 5.0.0.0 of System.Windows.Forms.Ribbon, .Net Framework 4.7.1, Form class set to inherit from RibbonForm instead of Form.
1) When running standard demos or my own forms I get a blue border on the window frame.
2) When designer has set orb style to 2007 then changing orb style to 2010 or 2013 at run time the tab title background goes black, this does not occur when designer has set orb style to 2010 or 2013.
When Form class does not inherit from RibbonForm, but inherits from Form, the blue border does not appear and the black tab title background does not occur.

Have tried building with .Net 2.0 but this makes no difference.

Thanks for any suggestions.
Jeff

**Comment by adriancs2** [comment]
It is not compatible with Windows 10. perhaps the ribbon form need to redo/redraw in coding.

**Comment by hausmaen** [comment]
Could you explain the "redo/redraw" a little more in detail? I can't find a methods to redraw control. Or is there a plan to make library Windows 10 compatible?

**Comment by adriancs2** [comment]
"Redo/redraw"  is to be done at the coding side. The project coding need to be improved to make this library compatible with Windows 10. Most of the senior team member have either gone inactivity or left the project since the migration from codeplex to github. There is currently no active member at the moment to contribute. If you have found the bug fixes, you are welcome to contribute it to the repository.

**Comment by adriancs2** [comment]
This problem is fixed in latest version, you may try out the nuget version.
Guide: How to add the ribbon library via Nuget:
https://github.com/RibbonWinForms/RibbonWinForms/wiki
